name: Terraform
on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: output terraform version from .tool-versions
        id: terraform-version
        run: echo "version=$(grep terraform .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.terraform-version.outputs.version }}
      - name: terraform fmt
        run: terraform fmt -check -recursive
